name: Daily Sun Times Update
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run generate
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cities/
          git commit -m "Update sun times for $(date)" || exit 0
          git push